### ISSUE TITLE
Test 3 gives errors

### ISSUE THREAD

**Issue by dvats** [pvarshney1729/GSoC2020_mcmcse_tests_solutions#1]
An independent run of test 3 gives errors. Please fix the issue.

**Comment by pvarshney1729** [comment]
I have corrected the code. There was an uninitialized variable issue. Kindly check.

**Comment by pvarshney1729** [comment]
Respected Ma'am,

I hope my submitted solutions turned out to be okay. If so, I would be
obliged if you could let me know if and how I should proceed with the
drafting of the GSoC proposal.

Thank You
Regards
Prateek Varshney
